
export type ComponentType =
  | 'ElDivider'
  | 'ElInput'
  | 'ElSelect'
  | 'ElDatePicker'
  | 'ElTimePicker'
  | 'ElRadio'
  | 'ElRadioGroup'
  | 'ElRadioButton'
  | 'ElCheckbox'
  | 'ElCheckboxGroup'
  | 'ElSwitch'
  | 'ElCascader'
  | 'ElRate'
  | 'ElSlider'
  | 'ElInputNumber'
